### ISSUE TITLE
UI Design and Prototypes - In Game UI

### ISSUE THREAD

**Issue by sagittaeri** [WatercressStudios/Yurijam2019#1]
- CTC
- Side image

**Comment by DreadLindwyrm** [comment]
UI 1920x1080
Textbox suggested to be 185px high, namebox 36 px high.

Font so far unknown??

Using side image.

Voiderling provided four frames for CTC indicator.

**Comment by sagittaeri** [comment]
Currently using this artist's BGs as test backgrounds to test my UI against: https://www.deviantart.com/bezduch/gallery

**Comment by sagittaeri** [comment]
Only Preferences Menu is left, and perhaps additional Quick Buttons to supplement or replace Flower Menu.

**Comment by Happiness-plus** [comment]
also done
